version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: node:9.7.1-alpine
        environment:
          NODE_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: digit
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: digit
          POSTGRES_PASSWORD: digit
          POSTGRES_DB: digit_testing
    steps: 
      - checkout
      - run: 
          name: Install dependencies
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: 
          name: Run DB migrations
          command: node ./db/migrate-up.js
      - run: 
          name: Run tests
          command: npm test
